version: '3'
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
