version: '3'
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "5000:5000"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - nginx-proxy-network
      - nodejs-app-network

networks:
  nginx-proxy-network:
    driver: bridge
  nodejs-app-network:
    external: true
    name: nodejs-github-stack_app-network
